import os
import pickle
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Rectangle

# --- CONFIG ---
# Update these to match your remote setup
REMOTE_USER = "laz"
REMOTE_HOST = "phoenix.wordwaves.app"
REMOTE_DIR = "~/mmr-elites"  # Directory where scripts ran
LOCAL_DIR = "."

# Filenames generated by the remote scripts
FILE_MAP = "map_elites_ant_results.pkl"
FILE_MUSE = "muse_ant_results.pkl"

def download_data():
    """Fetches the latest results from the remote server."""
    print(f"📡 Connecting to {REMOTE_HOST}...")
    
    for f_name in [FILE_MAP, FILE_MUSE]:
        remote_path = f"{REMOTE_DIR}/{f_name}"
        local_path = f"{LOCAL_DIR}/{f_name}"
        
        cmd = f"scp {REMOTE_USER}@{REMOTE_HOST}:{remote_path} {local_path}"
        print(f"   Downloading {f_name}...")
        if os.system(cmd) != 0:
            print(f"   ⚠️ Warning: Could not download {f_name} (Maybe experiment isn't finished?)")
        else:
            print(f"   ✅ {f_name} retrieved.")

def load_pkl(filename):
    if not os.path.exists(filename):
        return None
    with open(filename, "rb") as f:
        return pickle.load(f)

def analyze():
    # 1. Load Data
    me_data = load_pkl(FILE_MAP)
    muse_data = load_pkl(FILE_MUSE)
    
    if me_data is None and muse_data is None:
        print("❌ No data found. Check SCP connection."); return

    fig = plt.figure(figsize=(16, 10))
    gs = fig.add_gridspec(2, 2)
    
    # --- PLOT 1 & 2: REACHABILITY MAPS (Scatter) ---
    # We plot these side-by-side on the top row
    
    axes = [fig.add_subplot(gs[0, 0]), fig.add_subplot(gs[0, 1])]
    datasets = [("MAP-Elites", me_data), ("MUSE-QD", muse_data)]
    
    for ax, (name, data) in zip(axes, datasets):
        if data is None:
            ax.text(0.5, 0.5, "Data Missing", ha='center'); continue
            
        # Extract descriptors (Positions)
        # Note: Keys differ slightly based on our previous scripts
        if "final_descriptors" in data:
            # Our standard format
            pts = data["final_descriptors"]
        else:
            # Fallback if structure varies
            print(f"⚠️ Key error in {name}"); continue
            
        # Metrics
        count = len(pts)
        max_dist = np.max(np.linalg.norm(pts, axis=1)) if count > 0 else 0
        
        # Plot
        dists = np.linalg.norm(pts, axis=1)
        sc = ax.scatter(pts[:, 0], pts[:, 1], c=dists, cmap='turbo', s=15, alpha=0.6, edgecolors='none')
        
        # Decorations
        ax.set_title(f"{name}\nArchive: {count} | Max Dist: {max_dist:.1f}m", fontsize=12, fontweight='bold')
        ax.set_xlim(-35, 35); ax.set_ylim(-35, 35)
        ax.set_aspect('equal')
        ax.grid(True, alpha=0.2, linestyle='--')
        
        # Draw the "Grid Box" (Where MAP-Elites lives)
        rect = Rectangle((-30, -30), 60, 60, linewidth=1, edgecolor='r', facecolor='none', linestyle='--')
        ax.add_patch(rect)
        if name == "MAP-Elites":
            ax.text(-28, 28, "Grid Bounds", color='red', fontsize=8)

    # Colorbar for the top row
    cbar = fig.colorbar(sc, ax=axes, orientation='vertical', fraction=0.02, pad=0.02)
    cbar.set_label("Distance (m)")

    # --- PLOT 3: DISCOVERY CURVES (Line Plot) ---
    # Bottom row, spanning both columns
    ax_hist = fig.add_subplot(gs[1, :])
    
    # Plot MAP-Elites History
    if me_data and "history_max_fit" in me_data:
        gens = me_data.get("history_gen", range(len(me_data["history_max_fit"])))
        ax_hist.plot(gens, me_data["history_max_fit"], 'b--', linewidth=2, label="MAP-Elites (Max Fit)")
        
    # Plot MUSE-QD History
    if muse_data and "history" in muse_data:
        # Our MUSE script stored history in a sub-dict
        h = muse_data["history"]
        ax_hist.plot(h["gen"], h["max_fit"], 'r-', linewidth=2, label="MUSE-QD (Max Fit)")
    
    ax_hist.set_title("Learning Curve: Peak Performance over Time", fontsize=12)
    ax_hist.set_xlabel("Generations")
    ax_hist.set_ylabel("Fitness (Distance + Survival)")
    ax_hist.grid(True, alpha=0.3)
    ax_hist.legend()

    plt.tight_layout()
    plt.show()

    # --- TEXT REPORT ---
    print("\n📊 BATTLE REPORT")
    print("-" * 40)
    for name, data in datasets:
        if data is None: continue
        pts = data["final_descriptors"]
        
        # Calculate "Spread" (Convex Hull Area or Variance)
        # Simple variance is a robust proxy for diversity spread
        spread_x = np.var(pts[:, 0])
        spread_y = np.var(pts[:, 1])
        total_spread = spread_x + spread_y
        
        # Archive Size
        size = len(pts)
        
        print(f"🔹 {name}")
        print(f"   • Archive Size: {size}")
        print(f"   • Diversity Score (Variance): {total_spread:.2f}")
        print("-" * 40)

if __name__ == "__main__":
    download_data()
    analyze()
